import iconFlagRD from "../../assets/icons/flag-rd.svg";
import iconFlagUS from "../../assets/icons/flag-usa.svg";

// Objeto con listado completo de todos los países del mundo con datos detallados (196 países)
const countriesData = [
  {
    idCountry: 1,
    flag: "🇩🇴",
    code: "DO",
    countryName: "República Dominicana",
    cityName: "Santo Domingo",
    phoneCode: ["+1809", "+1829", "+1849"],
    currency: "DOP",
    language: "Español",
    region: "Caribe",
    timezone: "GMT-4",
    population: 10847910,
    coordinates: { lat: 18.4861, lng: -69.9312 },
    domain: ".do",
    flagSVG: "DoFlag",
    gentilicio: "Dominicano"
  },
  {
    idCountry: 2,
    flag: "🇺🇸",
    code: "US",
    countryName: "Estados Unidos",
    cityName: "Washington D.C.",
    phoneCode: "+1",
    currency: "USD",
    language: "Inglés",
    region: "Norteamérica",
    timezone: "GMT-4 a GMT-10",
    population: 331002651,
    coordinates: { lat: 38.9072, lng: -77.0369 },
    domain: ".us",
    flagSVG: "UsFlag",
    gentilicio: "Estadounidense"
  },
  {
    idCountry: 3,
    flag: "🇦🇫",
    code: "AF",
    countryName: "Afganistán",
    cityName: "Kabul",
    phoneCode: "+93",
    currency: "AFN",
    language: "Dari, Pashto",
    region: "Asia",
    timezone: "GMT+4:30",
    population: 38928346,
    coordinates: { lat: 34.5553, lng: 69.2075 },
    domain: ".af",
    flagSVG: "AfFlag",
    gentilicio: "Afgano"
  },
  {
    idCountry: 4,
    flag: "🇦🇱",
    code: "AL",
    countryName: "Albania",
    cityName: "Tirana",
    phoneCode: "+355",
    currency: "ALL",
    language: "Albanés",
    region: "Europa",
    timezone: "GMT+2",
    population: 2877797,
    coordinates: { lat: 41.3275, lng: 19.8187 },
    domain: ".al",
    flagSVG: "AlFlag",
    gentilicio: "Albanés"
  },
  {
    idCountry: 5,
    flag: "🇩🇪",
    code: "DE",
    countryName: "Alemania",
    cityName: "Berlín",
    phoneCode: "+49",
    currency: "EUR",
    language: "Alemán",
    region: "Europa",
    timezone: "GMT+2",
    population: 83783942,
    coordinates: { lat: 52.52, lng: 13.405 },
    domain: ".de",
    flagSVG: "DeFlag",
    gentilicio: "Alemán"
  },
  {
    idCountry: 6,
    flag: "🇦🇩",
    code: "AD",
    countryName: "Andorra",
    cityName: "Andorra la Vella",
    phoneCode: "+376",
    currency: "EUR",
    language: "Catalán",
    region: "Europa",
    timezone: "GMT+2",
    population: 77265,
    coordinates: { lat: 42.5063, lng: 1.5218 },
    domain: ".ad",
    flagSVG: "AdFlag",
    gentilicio: "Andorrano"
  },
  {
    idCountry: 7,
    flag: "🇦🇴",
    code: "AO",
    countryName: "Angola",
    cityName: "Luanda",
    phoneCode: "+244",
    currency: "AOA",
    language: "Portugués",
    region: "África",
    timezone: "GMT+1",
    population: 32866272,
    coordinates: { lat: -8.839, lng: 13.2894 },
    domain: ".ao",
    flagSVG: "AoFlag",
    gentilicio: "Angoleño"
  },
  {
    idCountry: 8,
    flag: "🇦🇬",
    code: "AG",
    countryName: "Antigua y Barbuda",
    cityName: "Saint John's",
    phoneCode: "+1268",
    currency: "XCD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 97929,
    coordinates: { lat: 17.1274, lng: -61.8468 },
    domain: ".ag",
    flagSVG: "AgFlag",
    gentilicio: "Antigüeño"
  },
  {
    idCountry: 9,
    flag: "🇸🇦",
    code: "SA",
    countryName: "Arabia Saudí",
    cityName: "Riad",
    phoneCode: "+966",
    currency: "SAR",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 34813871,
    coordinates: { lat: 24.7136, lng: 46.6753 },
    domain: ".sa",
    flagSVG: "SaFlag",
    gentilicio: "Saudí"
  },
  {
    idCountry: 10,
    flag: "🇩🇿",
    code: "DZ",
    countryName: "Argelia",
    cityName: "Argel",
    phoneCode: "+213",
    currency: "DZD",
    language: "Árabe, Bereber",
    region: "África",
    timezone: "GMT+1",
    population: 43851044,
    coordinates: { lat: 36.7538, lng: 3.0588 },
    domain: ".dz",
    flagSVG: "DzFlag",
    gentilicio: "Argelino"
  },
  {
    idCountry: 11,
    flag: "🇦🇷",
    code: "AR",
    countryName: "Argentina",
    cityName: "Buenos Aires",
    phoneCode: "+54",
    currency: "ARS",
    language: "Español",
    region: "Sudamérica",
    timezone: "GMT-3",
    population: 45195774,
    coordinates: { lat: -34.6037, lng: -58.3816 },
    domain: ".ar",
    flagSVG: "ArFlag",
    gentilicio: "Argentino"
  },
  {
    idCountry: 12,
    flag: "🇦🇲",
    code: "AM",
    countryName: "Armenia",
    cityName: "Ereván",
    phoneCode: "+374",
    currency: "AMD",
    language: "Armenio",
    region: "Asia",
    timezone: "GMT+4",
    population: 2963243,
    coordinates: { lat: 40.1792, lng: 44.4991 },
    domain: ".am",
    flagSVG: "AmFlag",
    gentilicio: "Armenio"
  },
  {
    idCountry: 13,
    flag: "🇦🇺",
    code: "AU",
    countryName: "Australia",
    cityName: "Canberra",
    phoneCode: "+61",
    currency: "AUD",
    language: "Inglés",
    region: "Oceanía",
    timezone: "GMT+10",
    population: 25499884,
    coordinates: { lat: -35.2809, lng: 149.13 },
    domain: ".au",
    flagSVG: "AuFlag",
    gentilicio: "Australiano"
  },
  {
    idCountry: 14,
    flag: "🇦🇹",
    code: "AT",
    countryName: "Austria",
    cityName: "Viena",
    phoneCode: "+43",
    currency: "EUR",
    language: "Alemán",
    region: "Europa",
    timezone: "GMT+2",
    population: 9006398,
    coordinates: { lat: 48.2082, lng: 16.3738 },
    domain: ".at",
    flagSVG: "AtFlag",
    gentilicio: "Austriaco"
  },
  {
    idCountry: 15,
    flag: "🇦🇿",
    code: "AZ",
    countryName: "Azerbaiyán",
    cityName: "Bakú",
    phoneCode: "+994",
    currency: "AZN",
    language: "Azerí",
    region: "Asia",
    timezone: "GMT+4",
    population: 10139177,
    coordinates: { lat: 40.4093, lng: 49.8671 },
    domain: ".az",
    flagSVG: "AzFlag",
    gentilicio: "Azerbaiyano"
  },
  {
    idCountry: 16,
    flag: "🇧🇸",
    code: "BS",
    countryName: "Bahamas",
    cityName: "Nasáu",
    phoneCode: "+1242",
    currency: "BSD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 393244,
    coordinates: { lat: 25.0343, lng: -77.3963 },
    domain: ".bs",
    flagSVG: "BsFlag",
    gentilicio: "Bahameño"
  },
  {
    idCountry: 17,
    flag: "🇧🇩",
    code: "BD",
    countryName: "Bangladés",
    cityName: "Daca",
    phoneCode: "+880",
    currency: "BDT",
    language: "Bengalí",
    region: "Asia",
    timezone: "GMT+6",
    population: 164689383,
    coordinates: { lat: 23.8103, lng: 90.4125 },
    domain: ".bd",
    flagSVG: "BdFlag",
    gentilicio: "Bangladesí"
  },
  {
    idCountry: 18,
    flag: "🇧🇧",
    code: "BB",
    countryName: "Barbados",
    cityName: "Bridgetown",
    phoneCode: "+1246",
    currency: "BBD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 287375,
    coordinates: { lat: 13.1939, lng: -59.5432 },
    domain: ".bb",
    flagSVG: "BbFlag",
    gentilicio: "Barbadense"
  },
  {
    idCountry: 19,
    flag: "🇧🇭",
    code: "BH",
    countryName: "Baréin",
    cityName: "Manama",
    phoneCode: "+973",
    currency: "BHD",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 1701575,
    coordinates: { lat: 26.2285, lng: 50.586 },
    domain: ".bh",
    flagSVG: "BhFlag",
    gentilicio: "Bareiní"
  },
  {
    idCountry: 20,
    flag: "🇧🇪",
    code: "BE",
    countryName: "Bélgica",
    cityName: "Bruselas",
    phoneCode: "+32",
    currency: "EUR",
    language: "Neerlandés, Francés",
    region: "Europa",
    timezone: "GMT+2",
    population: 11589623,
    coordinates: { lat: 50.8503, lng: 4.3517 },
    domain: ".be",
    flagSVG: "BeFlag",
    gentilicio: "Belga"
  },
  {
    idCountry: 21,
    flag: "🇧🇿",
    code: "BZ",
    countryName: "Belice",
    cityName: "Belmopán",
    phoneCode: "+501",
    currency: "BZD",
    language: "Inglés",
    region: "Centroamérica",
    timezone: "GMT-6",
    population: 397628,
    coordinates: { lat: 17.2514, lng: -88.769 },
    domain: ".bz",
    flagSVG: "BzFlag",
    gentilicio: "Beliceño"
  },
  {
    idCountry: 22,
    flag: "🇧🇯",
    code: "BJ",
    countryName: "Benín",
    cityName: "Porto-Novo",
    phoneCode: "+229",
    currency: "XOF",
    language: "Francés",
    region: "África",
    timezone: "GMT+1",
    population: 12123200,
    coordinates: { lat: 6.4969, lng: 2.6283 },
    domain: ".bj",
    flagSVG: "BjFlag",
    gentilicio: "Beninés"
  },
  {
    idCountry: 23,
    flag: "🇧🇾",
    code: "BY",
    countryName: "Bielorrusia",
    cityName: "Minsk",
    phoneCode: "+375",
    currency: "BYN",
    language: "Bielorruso, Ruso",
    region: "Europa",
    timezone: "GMT+3",
    population: 9449323,
    coordinates: { lat: 53.9045, lng: 27.5615 },
    domain: ".by",
    flagSVG: "ByFlag",
    gentilicio: "Bielorruso"
  },
  {
    idCountry: 24,
    flag: "🇧🇴",
    code: "BO",
    countryName: "Bolivia",
    cityName: "Sucre",
    phoneCode: "+591",
    currency: "BOB",
    language: "Español, Quechua",
    region: "Sudamérica",
    timezone: "GMT-4",
    population: 11673021,
    coordinates: { lat: -19.0368, lng: -65.2592 },
    domain: ".bo",
    flagSVG: "BoFlag",
    gentilicio: "Boliviano"
  },
  {
    idCountry: 25,
    flag: "🇧🇦",
    code: "BA",
    countryName: "Bosnia y Herzegovina",
    cityName: "Sarajevo",
    phoneCode: "+387",
    currency: "BAM",
    language: "Bosnio, Croata",
    region: "Europa",
    timezone: "GMT+2",
    population: 3280819,
    coordinates: { lat: 43.8563, lng: 18.4131 },
    domain: ".ba",
    flagSVG: "BaFlag",
    gentilicio: "Bosnio"
  },
  {
    idCountry: 26,
    flag: "🇧🇼",
    code: "BW",
    countryName: "Botsuana",
    cityName: "Gaborone",
    phoneCode: "+267",
    currency: "BWP",
    language: "Inglés, Setsuana",
    region: "África",
    timezone: "GMT+2",
    population: 2351627,
    coordinates: { lat: -24.6282, lng: 25.9231 },
    domain: ".bw",
    flagSVG: "BwFlag",
    gentilicio: "Botsuano"
  },
  {
    idCountry: 27,
    flag: "🇧🇷",
    code: "BR",
    countryName: "Brasil",
    cityName: "Brasilia",
    phoneCode: "+55",
    currency: "BRL",
    language: "Portugués",
    region: "Sudamérica",
    timezone: "GMT-3",
    population: 212559417,
    coordinates: { lat: -15.7801, lng: -47.9292 },
    domain: ".br",
    flagSVG: "BrFlag",
    gentilicio: "Brasileño"
  },
  {
    idCountry: 28,
    flag: "🇧🇳",
    code: "BN",
    countryName: "Brunéi",
    cityName: "Bandar Seri Begawan",
    phoneCode: "+673",
    currency: "BND",
    language: "Malayo",
    region: "Asia",
    timezone: "GMT+8",
    population: 437479,
    coordinates: { lat: 4.9031, lng: 114.9398 },
    domain: ".bn",
    flagSVG: "BnFlag",
    gentilicio: "Bruneano"
  },
  {
    idCountry: 29,
    flag: "🇧🇬",
    code: "BG",
    countryName: "Bulgaria",
    cityName: "Sofía",
    phoneCode: "+359",
    currency: "BGN",
    language: "Búlgaro",
    region: "Europa",
    timezone: "GMT+3",
    population: 6948445,
    coordinates: { lat: 42.6977, lng: 23.3219 },
    domain: ".bg",
    flagSVG: "BgFlag",
    gentilicio: "Búlgaro"
  },
  {
    idCountry: 30,
    flag: "🇧🇫",
    code: "BF",
    countryName: "Burkina Faso",
    cityName: "Uagadugú",
    phoneCode: "+226",
    currency: "XOF",
    language: "Francés",
    region: "África",
    timezone: "GMT+0",
    population: 20903273,
    coordinates: { lat: 12.3714, lng: -1.5197 },
    domain: ".bf",
    flagSVG: "BfFlag",
    gentilicio: "Burkinés"
  },
  {
    idCountry: 31,
    flag: "🇧🇮",
    code: "BI",
    countryName: "Burundi",
    cityName: "Gitega",
    phoneCode: "+257",
    currency: "BIF",
    language: "Kirundi, Francés",
    region: "África",
    timezone: "GMT+2",
    population: 11890784,
    coordinates: { lat: -3.3428, lng: 29.9196 },
    domain: ".bi",
    flagSVG: "BiFlag",
    gentilicio: "Burundés"
  },
  {
    idCountry: 32,
    flag: "🇧🇹",
    code: "BT",
    countryName: "Bután",
    cityName: "Timbu",
    phoneCode: "+975",
    currency: "BTN",
    language: "Dzongkha",
    region: "Asia",
    timezone: "GMT+6",
    population: 771608,
    coordinates: { lat: 27.4728, lng: 89.639 },
    domain: ".bt",
    flagSVG: "BtFlag",
    gentilicio: "Butanés"
  },
  {
    idCountry: 33,
    flag: "🇨🇻",
    code: "CV",
    countryName: "Cabo Verde",
    cityName: "Praia",
    phoneCode: "+238",
    currency: "CVE",
    language: "Portugués",
    region: "África",
    timezone: "GMT-1",
    population: 555987,
    coordinates: { lat: 14.9315, lng: -23.5133 },
    domain: ".cv",
    flagSVG: "CvFlag",
    gentilicio: "Caboverdiano"
  },
  {
    idCountry: 34,
    flag: "🇰🇭",
    code: "KH",
    countryName: "Camboya",
    cityName: "Nom Pen",
    phoneCode: "+855",
    currency: "KHR",
    language: "Jemer",
    region: "Asia",
    timezone: "GMT+7",
    population: 16718965,
    coordinates: { lat: 11.5556, lng: 104.9282 },
    domain: ".kh",
    flagSVG: "KhFlag",
    gentilicio: "Camboyano"
  },
  {
    idCountry: 35,
    flag: "🇨🇲",
    code: "CM",
    countryName: "Camerún",
    cityName: "Yaundé",
    phoneCode: "+237",
    currency: "XAF",
    language: "Inglés, Francés",
    region: "África",
    timezone: "GMT+1",
    population: 26545863,
    coordinates: { lat: 3.848, lng: 11.5021 },
    domain: ".cm",
    flagSVG: "CmFlag",
    gentilicio: "Camerunés"
  },
  {
    idCountry: 36,
    flag: "🇨🇦",
    code: "CA",
    countryName: "Canadá",
    cityName: "Ottawa",
    phoneCode: "+1",
    currency: "CAD",
    language: "Inglés, Francés",
    region: "Norteamérica",
    timezone: "GMT-4 a GMT-8",
    population: 37742154,
    coordinates: { lat: 45.4215, lng: -75.6972 },
    domain: ".ca",
    flagSVG: "CaFlag",
    gentilicio: "Canadiense"
  },
  {
    idCountry: 37,
    flag: "🇶🇦",
    code: "QA",
    countryName: "Catar",
    cityName: "Doha",
    phoneCode: "+974",
    currency: "QAR",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 2881053,
    coordinates: { lat: 25.276, lng: 51.52 },
    domain: ".qa",
    flagSVG: "QaFlag",
    gentilicio: "Catarí"
  },
  {
    idCountry: 38,
    flag: "🇹🇩",
    code: "TD",
    countryName: "Chad",
    cityName: "Yamena",
    phoneCode: "+235",
    currency: "XAF",
    language: "Francés, Árabe",
    region: "África",
    timezone: "GMT+1",
    population: 16425864,
    coordinates: { lat: 12.1348, lng: 15.0557 },
    domain: ".td",
    flagSVG: "TdFlag",
    gentilicio: "Chadiano"
  },
  {
    idCountry: 39,
    flag: "🇨🇱",
    code: "CL",
    countryName: "Chile",
    cityName: "Santiago",
    phoneCode: "+56",
    currency: "CLP",
    language: "Español",
    region: "Sudamérica",
    timezone: "GMT-3",
    population: 19116201,
    coordinates: { lat: -33.4489, lng: -70.6693 },
    domain: ".cl",
    flagSVG: "ClFlag",
    gentilicio: "Chileno"
  },
  {
    idCountry: 40,
    flag: "🇨🇳",
    code: "CN",
    countryName: "China",
    cityName: "Beijing",
    phoneCode: "+86",
    currency: "CNY",
    language: "Mandarín",
    region: "Asia",
    timezone: "GMT+8",
    population: 1439323776,
    coordinates: { lat: 39.9042, lng: 116.4074 },
    domain: ".cn",
    flagSVG: "CnFlag",
    gentilicio: "Chino"
  },
  {
    idCountry: 41,
    flag: "🇨🇾",
    code: "CY",
    countryName: "Chipre",
    cityName: "Nicosia",
    phoneCode: "+357",
    currency: "EUR",
    language: "Griego, Turco",
    region: "Europa/Asia",
    timezone: "GMT+3",
    population: 1207359,
    coordinates: { lat: 35.1856, lng: 33.3823 },
    domain: ".cy",
    flagSVG: "CyFlag",
    gentilicio: "Chipriota"
  },
  {
    idCountry: 42,
    flag: "🇻🇦",
    code: "VA",
    countryName: "Ciudad del Vaticano",
    cityName: "Vaticano",
    phoneCode: "+39",
    currency: "EUR",
    language: "Latín, Italiano",
    region: "Europa",
    timezone: "GMT+2",
    population: 825,
    coordinates: { lat: 41.9029, lng: 12.4534 },
    domain: ".va",
    flagSVG: "VaFlag",
    gentilicio: "Vaticano"
  },
  {
    idCountry: 43,
    flag: "🇨🇴",
    code: "CO",
    countryName: "Colombia",
    cityName: "Bogotá",
    phoneCode: "+57",
    currency: "COP",
    language: "Español",
    region: "Sudamérica",
    timezone: "GMT-5",
    population: 50882891,
    coordinates: { lat: 4.711, lng: -74.0721 },
    domain: ".co",
    flagSVG: "CoFlag",
    gentilicio: "Colombiano"
  },
  {
    idCountry: 44,
    flag: "🇰🇲",
    code: "KM",
    countryName: "Comoras",
    cityName: "Moroni",
    phoneCode: "+269",
    currency: "KMF",
    language: "Árabe, Francés",
    region: "África",
    timezone: "GMT+3",
    population: 869601,
    coordinates: { lat: -11.6455, lng: 43.3333 },
    domain: ".km",
    flagSVG: "KmFlag",
    gentilicio: "Comorense"
  },
  {
    idCountry: 45,
    flag: "🇰🇵",
    code: "KP",
    countryName: "Corea del Norte",
    cityName: "Pyongyang",
    phoneCode: "+850",
    currency: "KPW",
    language: "Coreano",
    region: "Asia",
    timezone: "GMT+9",
    population: 25778816,
    coordinates: { lat: 39.0392, lng: 125.7625 },
    domain: ".kp",
    flagSVG: "KpFlag",
    gentilicio: "Norcoreano"
  },
  {
    idCountry: 46,
    flag: "🇰🇷",
    code: "KR",
    countryName: "Corea del Sur",
    cityName: "Seúl",
    phoneCode: "+82",
    currency: "KRW",
    language: "Coreano",
    region: "Asia",
    timezone: "GMT+9",
    population: 51269185,
    coordinates: { lat: 37.5665, lng: 126.978 },
    domain: ".kr",
    flagSVG: "KrFlag",
    gentilicio: "Surcoreano"
  },
  {
    idCountry: 47,
    flag: "🇨🇷",
    code: "CR",
    countryName: "Costa Rica",
    cityName: "San José",
    phoneCode: "+506",
    currency: "CRC",
    language: "Español",
    region: "Centroamérica",
    timezone: "GMT-6",
    population: 5094118,
    coordinates: { lat: 9.9281, lng: -84.0907 },
    domain: ".cr",
    flagSVG: "CrFlag",
    gentilicio: "Costarricense"
  },
  {
    idCountry: 48,
    flag: "🇨🇮",
    code: "CI",
    countryName: "Costa de Marfil",
    cityName: "Yamusukro",
    phoneCode: "+225",
    currency: "XOF",
    language: "Francés",
    region: "África",
    timezone: "GMT+0",
    population: 26378274,
    coordinates: { lat: 6.8276, lng: -5.2893 },
    domain: ".ci",
    flagSVG: "CiFlag",
    gentilicio: "Marfileño"
  },
  {
    idCountry: 49,
    flag: "🇭🇷",
    code: "HR",
    countryName: "Croacia",
    cityName: "Zagreb",
    phoneCode: "+385",
    currency: "HRK",
    language: "Croata",
    region: "Europa",
    timezone: "GMT+2",
    population: 4105267,
    coordinates: { lat: 45.815, lng: 15.9819 },
    domain: ".hr",
    flagSVG: "HrFlag",
    gentilicio: "Croata"
  },
  {
    idCountry: 50,
    flag: "🇨🇺",
    code: "CU",
    countryName: "Cuba",
    cityName: "La Habana",
    phoneCode: "+53",
    currency: "CUP",
    language: "Español",
    region: "Caribe",
    timezone: "GMT-4",
    population: 11326616,
    coordinates: { lat: 23.1136, lng: -82.3666 },
    domain: ".cu",
    flagSVG: "CuFlag",
    gentilicio: "Cubano"
  },
  // PARTE 2: Países 51-100
  {
    idCountry: 51,
    flag: "🇩🇰",
    code: "DK",
    countryName: "Dinamarca",
    cityName: "Copenhague",
    phoneCode: "+45",
    currency: "DKK",
    language: "Danés",
    region: "Europa",
    timezone: "GMT+2",
    population: 5792202,
    coordinates: { lat: 55.6761, lng: 12.5683 },
    domain: ".dk",
    flagSVG: "DkFlag",
    gentilicio: "Danés"
  },
  {
    idCountry: 52,
    flag: "🇩🇲",
    code: "DM",
    countryName: "Dominica",
    cityName: "Roseau",
    phoneCode: "+1767",
    currency: "XCD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 71986,
    coordinates: { lat: 15.301, lng: -61.387 },
    domain: ".dm",
    flagSVG: "DmFlag",
    gentilicio: "Dominiqués"
  },
  {
    idCountry: 53,
    flag: "🇪🇨",
    code: "EC",
    countryName: "Ecuador",
    cityName: "Quito",
    phoneCode: "+593",
    currency: "USD",
    language: "Español",
    region: "Sudamérica",
    timezone: "GMT-5",
    population: 17643054,
    coordinates: { lat: -0.1807, lng: -78.4678 },
    domain: ".ec",
    flagSVG: "EcFlag",
    gentilicio: "Ecuatoriano"
  },
  {
    idCountry: 54,
    flag: "🇪🇬",
    code: "EG",
    countryName: "Egipto",
    cityName: "El Cairo",
    phoneCode: "+20",
    currency: "EGP",
    language: "Árabe",
    region: "África",
    timezone: "GMT+2",
    population: 102334404,
    coordinates: { lat: 30.0444, lng: 31.2357 },
    domain: ".eg",
    flagSVG: "EgFlag",
    gentilicio: "Egipcio"
  },
  {
    idCountry: 55,
    flag: "🇸🇻",
    code: "SV",
    countryName: "El Salvador",
    cityName: "San Salvador",
    phoneCode: "+503",
    currency: "USD",
    language: "Español",
    region: "Centroamérica",
    timezone: "GMT-6",
    population: 6486205,
    coordinates: { lat: 13.6929, lng: -89.2182 },
    domain: ".sv",
    flagSVG: "SvFlag",
    gentilicio: "Salvadoreño"
  },
  {
    idCountry: 56,
    flag: "🇦🇪",
    code: "AE",
    countryName: "Emiratos Árabes Unidos",
    cityName: "Abu Dabi",
    phoneCode: "+971",
    currency: "AED",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+4",
    population: 9890402,
    coordinates: { lat: 24.2992, lng: 54.6975 },
    domain: ".ae",
    flagSVG: "AeFlag",
    gentilicio: "Emiratí"
  },
  {
    idCountry: 57,
    flag: "🇪🇷",
    code: "ER",
    countryName: "Eritrea",
    cityName: "Asmara",
    phoneCode: "+291",
    currency: "ERN",
    language: "Tigriña, Árabe",
    region: "África",
    timezone: "GMT+3",
    population: 3546421,
    coordinates: { lat: 15.3229, lng: 38.9251 },
    domain: ".er",
    flagSVG: "ErFlag",
    gentilicio: "Eritreo"
  },
  {
    idCountry: 58,
    flag: "🇸🇰",
    code: "SK",
    countryName: "Eslovaquia",
    cityName: "Bratislava",
    phoneCode: "+421",
    currency: "EUR",
    language: "Eslovaco",
    region: "Europa",
    timezone: "GMT+2",
    population: 5459642,
    coordinates: { lat: 48.1486, lng: 17.1077 },
    domain: ".sk",
    flagSVG: "SkFlag",
    gentilicio: "Eslovaco"
  },
  {
    idCountry: 59,
    flag: "🇸🇮",
    code: "SI",
    countryName: "Eslovenia",
    cityName: "Liubliana",
    phoneCode: "+386",
    currency: "EUR",
    language: "Esloveno",
    region: "Europa",
    timezone: "GMT+2",
    population: 2078938,
    coordinates: { lat: 46.0569, lng: 14.5058 },
    domain: ".si",
    flagSVG: "SiFlag",
    gentilicio: "Esloveno"
  },
  {
    idCountry: 60,
    flag: "🇪🇸",
    code: "ES",
    countryName: "España",
    cityName: "Madrid",
    phoneCode: "+34",
    currency: "EUR",
    language: "Español",
    region: "Europa",
    timezone: "GMT+2",
    population: 46754778,
    coordinates: { lat: 40.4168, lng: -3.7038 },
    domain: ".es",
    flagSVG: "EsFlag",
    gentilicio: "Español"
  },
  {
    idCountry: 61,
    flag: "🇪🇪",
    code: "EE",
    countryName: "Estonia",
    cityName: "Tallin",
    phoneCode: "+372",
    currency: "EUR",
    language: "Estonio",
    region: "Europa",
    timezone: "GMT+3",
    population: 1326535,
    coordinates: { lat: 59.437, lng: 24.7536 },
    domain: ".ee",
    flagSVG: "EeFlag",
    gentilicio: "Estonio"
  },
  {
    idCountry: 62,
    flag: "🇸🇿",
    code: "SZ",
    countryName: "Esuatini",
    cityName: "Mbabane",
    phoneCode: "+268",
    currency: "SZL",
    language: "Inglés, Suazi",
    region: "África",
    timezone: "GMT+2",
    population: 1160164,
    coordinates: { lat: -26.5225, lng: 31.4659 },
    domain: ".sz",
    flagSVG: "SzFlag",
    gentilicio: "Suazi"
  },
  {
    idCountry: 63,
    flag: "🇪🇹",
    code: "ET",
    countryName: "Etiopía",
    cityName: "Adís Abeba",
    phoneCode: "+251",
    currency: "ETB",
    language: "Amárico",
    region: "África",
    timezone: "GMT+3",
    population: 114963588,
    coordinates: { lat: 9.0232, lng: 38.7468 },
    domain: ".et",
    flagSVG: "EtFlag",
    gentilicio: "Etíope"
  },
  {
    idCountry: 64,
    flag: "🇫🇯",
    code: "FJ",
    countryName: "Fiyi",
    cityName: "Suva",
    phoneCode: "+679",
    currency: "FJD",
    language: "Inglés, Fiyiano",
    region: "Oceanía",
    timezone: "GMT+12",
    population: 896445,
    coordinates: { lat: -18.1405, lng: 178.4213 },
    domain: ".fj",
    flagSVG: "FjFlag",
    gentilicio: "Fiyiano"
  },
  {
    idCountry: 65,
    flag: "🇵🇭",
    code: "PH",
    countryName: "Filipinas",
    cityName: "Manila",
    phoneCode: "+63",
    currency: "PHP",
    language: "Filipino, Inglés",
    region: "Asia",
    timezone: "GMT+8",
    population: 109581078,
    coordinates: { lat: 14.5995, lng: 120.9842 },
    domain: ".ph",
    flagSVG: "PhFlag",
    gentilicio: "Filipino"
  },
  {
    idCountry: 66,
    flag: "🇫🇮",
    code: "FI",
    countryName: "Finlandia",
    cityName: "Helsinki",
    phoneCode: "+358",
    currency: "EUR",
    language: "Finés, Sueco",
    region: "Europa",
    timezone: "GMT+3",
    population: 5540720,
    coordinates: { lat: 60.1699, lng: 24.9384 },
    domain: ".fi",
    flagSVG: "FiFlag",
    gentilicio: "Finlandés"
  },
  {
    idCountry: 67,
    flag: "🇫🇷",
    code: "FR",
    countryName: "Francia",
    cityName: "París",
    phoneCode: "+33",
    currency: "EUR",
    language: "Francés",
    region: "Europa",
    timezone: "GMT+2",
    population: 65273511,
    coordinates: { lat: 48.8566, lng: 2.3522 },
    domain: ".fr",
    flagSVG: "FrFlag",
    gentilicio: "Francés"
  },
  {
    idCountry: 68,
    flag: "🇬🇦",
    code: "GA",
    countryName: "Gabón",
    cityName: "Libreville",
    phoneCode: "+241",
    currency: "XAF",
    language: "Francés",
    region: "África",
    timezone: "GMT+1",
    population: 2225734,
    coordinates: { lat: 0.4162, lng: 9.4673 },
    domain: ".ga",
    flagSVG: "GaFlag",
    gentilicio: "Gabonés"
  },
  {
    idCountry: 69,
    flag: "🇬🇲",
    code: "GM",
    countryName: "Gambia",
    cityName: "Banjul",
    phoneCode: "+220",
    currency: "GMD",
    language: "Inglés",
    region: "África",
    timezone: "GMT+0",
    population: 2416668,
    coordinates: { lat: 13.4526, lng: -16.5775 },
    domain: ".gm",
    flagSVG: "GmFlag",
    gentilicio: "Gambiano"
  },
  {
    idCountry: 70,
    flag: "🇬🇪",
    code: "GE",
    countryName: "Georgia",
    cityName: "Tiflis",
    phoneCode: "+995",
    currency: "GEL",
    language: "Georgiano",
    region: "Asia",
    timezone: "GMT+4",
    population: 3989167,
    coordinates: { lat: 41.7151, lng: 44.8271 },
    domain: ".ge",
    flagSVG: "GeFlag",
    gentilicio: "Georgiano"
  },
  {
    idCountry: 71,
    flag: "🇬🇭",
    code: "GH",
    countryName: "Ghana",
    cityName: "Acra",
    phoneCode: "+233",
    currency: "GHS",
    language: "Inglés",
    region: "África",
    timezone: "GMT+0",
    population: 31072940,
    coordinates: { lat: 5.6037, lng: -0.187 },
    domain: ".gh",
    flagSVG: "GhFlag",
    gentilicio: "Ghanés"
  },
  {
    idCountry: 72,
    flag: "🇬🇩",
    code: "GD",
    countryName: "Granada",
    cityName: "Saint George's",
    phoneCode: "+1473",
    currency: "XCD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 112523,
    coordinates: { lat: 12.0562, lng: -61.7486 },
    domain: ".gd",
    flagSVG: "GdFlag",
    gentilicio: "Granadino"
  },
  {
    idCountry: 73,
    flag: "🇬🇷",
    code: "GR",
    countryName: "Grecia",
    cityName: "Atenas",
    phoneCode: "+30",
    currency: "EUR",
    language: "Griego",
    region: "Europa",
    timezone: "GMT+3",
    population: 10423054,
    coordinates: { lat: 37.9838, lng: 23.7275 },
    domain: ".gr",
    flagSVG: "GrFlag",
    gentilicio: "Griego"
  },
  {
    idCountry: 74,
    flag: "🇬🇹",
    code: "GT",
    countryName: "Guatemala",
    cityName: "Ciudad de Guatemala",
    phoneCode: "+502",
    currency: "GTQ",
    language: "Español",
    region: "Centroamérica",
    timezone: "GMT-6",
    population: 17915568,
    coordinates: { lat: 14.6349, lng: -90.5069 },
    domain: ".gt",
    flagSVG: "GtFlag",
    gentilicio: "Guatemalteco"
  },
  {
    idCountry: 75,
    flag: "🇬🇳",
    code: "GN",
    countryName: "Guinea",
    cityName: "Conakry",
    phoneCode: "+224",
    currency: "GNF",
    language: "Francés",
    region: "África",
    timezone: "GMT+0",
    population: 13132795,
    coordinates: { lat: 9.6412, lng: -13.5784 },
    domain: ".gn",
    flagSVG: "GnFlag",
    gentilicio: "Guineano"
  },
  {
    idCountry: 76,
    flag: "🇬🇶",
    code: "GQ",
    countryName: "Guinea Ecuatorial",
    cityName: "Malabo",
    phoneCode: "+240",
    currency: "XAF",
    language: "Español, Francés",
    region: "África",
    timezone: "GMT+1",
    population: 1402985,
    coordinates: { lat: 3.7504, lng: 8.7371 },
    domain: ".gq",
    flagSVG: "GqFlag",
    gentilicio: "Ecuatoguineano"
  },
  {
    idCountry: 77,
    flag: "🇬🇼",
    code: "GW",
    countryName: "Guinea-Bisáu",
    cityName: "Bisáu",
    phoneCode: "+245",
    currency: "XOF",
    language: "Portugués",
    region: "África",
    timezone: "GMT+0",
    population: 1968001,
    coordinates: { lat: 11.8815, lng: -15.6177 },
    domain: ".gw",
    flagSVG: "GwFlag",
    gentilicio: "Guineano-Bisauense"
  },
  {
    idCountry: 78,
    flag: "🇬🇾",
    code: "GY",
    countryName: "Guyana",
    cityName: "Georgetown",
    phoneCode: "+592",
    currency: "GYD",
    language: "Inglés",
    region: "Sudamérica",
    timezone: "GMT-4",
    population: 786552,
    coordinates: { lat: 6.8013, lng: -58.1551 },
    domain: ".gy",
    flagSVG: "GyFlag",
    gentilicio: "Guyanés"
  },
  {
    idCountry: 79,
    flag: "🇭🇹",
    code: "HT",
    countryName: "Haití",
    cityName: "Puerto Príncipe",
    phoneCode: "+509",
    currency: "HTG",
    language: "Francés, Criollo",
    region: "Caribe",
    timezone: "GMT-4",
    population: 11402528,
    coordinates: { lat: 18.5944, lng: -72.3074 },
    domain: ".ht",
    flagSVG: "HtFlag",
    gentilicio: "Haitiano"
  },
  {
    idCountry: 80,
    flag: "🇭🇳",
    code: "HN",
    countryName: "Honduras",
    cityName: "Tegucigalpa",
    phoneCode: "+504",
    currency: "HNL",
    language: "Español",
    region: "Centroamérica",
    timezone: "GMT-6",
    population: 9904607,
    coordinates: { lat: 14.0723, lng: -87.1921 },
    domain: ".hn",
    flagSVG: "HnFlag",
    gentilicio: "Hondureño"
  },
  {
    idCountry: 81,
    flag: "🇭🇺",
    code: "HU",
    countryName: "Hungría",
    cityName: "Budapest",
    phoneCode: "+36",
    currency: "HUF",
    language: "Húngaro",
    region: "Europa",
    timezone: "GMT+2",
    population: 9660351,
    coordinates: { lat: 47.4979, lng: 19.0402 },
    domain: ".hu",
    flagSVG: "HuFlag",
    gentilicio: "Húngaro"
  },
  {
    idCountry: 82,
    flag: "🇮🇳",
    code: "IN",
    countryName: "India",
    cityName: "Nueva Delhi",
    phoneCode: "+91",
    currency: "INR",
    language: "Hindi, Inglés",
    region: "Asia",
    timezone: "GMT+5:30",
    population: 1380004385,
    coordinates: { lat: 28.6139, lng: 77.209 },
    domain: ".in",
    flagSVG: "InFlag",
    gentilicio: "Indio"
  },
  {
    idCountry: 83,
    flag: "🇮🇩",
    code: "ID",
    countryName: "Indonesia",
    cityName: "Yakarta",
    phoneCode: "+62",
    currency: "IDR",
    language: "Indonesio",
    region: "Asia",
    timezone: "GMT+7",
    population: 273523615,
    coordinates: { lat: -6.2088, lng: 106.8456 },
    domain: ".id",
    flagSVG: "IdFlag",
    gentilicio: "Indonesio"
  },
  {
    idCountry: 84,
    flag: "🇮🇶",
    code: "IQ",
    countryName: "Irak",
    cityName: "Bagdad",
    phoneCode: "+964",
    currency: "IQD",
    language: "Árabe, Kurdo",
    region: "Asia",
    timezone: "GMT+3",
    population: 40222493,
    coordinates: { lat: 33.3152, lng: 44.3661 },
    domain: ".iq",
    flagSVG: "IqFlag",
    gentilicio: "Iraquí"
  },
  {
    idCountry: 85,
    flag: "🇮🇷",
    code: "IR",
    countryName: "Irán",
    cityName: "Teherán",
    phoneCode: "+98",
    currency: "IRR",
    language: "Persa",
    region: "Asia",
    timezone: "GMT+3:30",
    population: 83992949,
    coordinates: { lat: 35.6892, lng: 51.389 },
    domain: ".ir",
    flagSVG: "IrFlag",
    gentilicio: "Iraní"
  },
  {
    idCountry: 86,
    flag: "🇮🇪",
    code: "IE",
    countryName: "Irlanda",
    cityName: "Dublín",
    phoneCode: "+353",
    currency: "EUR",
    language: "Irlandés, Inglés",
    region: "Europa",
    timezone: "GMT+1",
    population: 4937786,
    coordinates: { lat: 53.3498, lng: -6.2603 },
    domain: ".ie",
    flagSVG: "IeFlag",
    gentilicio: "Irlandés"
  },
  {
    idCountry: 87,
    flag: "🇮🇸",
    code: "IS",
    countryName: "Islandia",
    cityName: "Reikiavik",
    phoneCode: "+354",
    currency: "ISK",
    language: "Islandés",
    region: "Europa",
    timezone: "GMT+0",
    population: 341243,
    coordinates: { lat: 64.1466, lng: -21.9426 },
    domain: ".is",
    flagSVG: "IsFlag",
    gentilicio: "Islandés"
  },
  {
    idCountry: 88,
    flag: "🇲🇭",
    code: "MH",
    countryName: "Islas Marshall",
    cityName: "Majuro",
    phoneCode: "+692",
    currency: "USD",
    language: "Inglés, Marshalés",
    region: "Oceanía",
    timezone: "GMT+12",
    population: 59190,
    coordinates: { lat: 7.1315, lng: 171.1845 },
    domain: ".mh",
    flagSVG: "MhFlag",
    gentilicio: "Marshalés"
  },
  {
    idCountry: 89,
    flag: "🇸🇧",
    code: "SB",
    countryName: "Islas Salomón",
    cityName: "Honiara",
    phoneCode: "+677",
    currency: "SBD",
    language: "Inglés",
    region: "Oceanía",
    timezone: "GMT+11",
    population: 686884,
    coordinates: { lat: -9.6457, lng: 160.1562 },
    domain: ".sb",
    flagSVG: "SbFlag",
    gentilicio: "Salomonense"
  },
  {
    idCountry: 90,
    flag: "🇮🇱",
    code: "IL",
    countryName: "Israel",
    cityName: "Jerusalén",
    phoneCode: "+972",
    currency: "ILS",
    language: "Hebreo, Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 8655535,
    coordinates: { lat: 31.7683, lng: 35.2137 },
    domain: ".il",
    flagSVG: "IlFlag",
    gentilicio: "Israelí"
  },
  {
    idCountry: 91,
    flag: "🇮🇹",
    code: "IT",
    countryName: "Italia",
    cityName: "Roma",
    phoneCode: "+39",
    currency: "EUR",
    language: "Italiano",
    region: "Europa",
    timezone: "GMT+2",
    population: 60461826,
    coordinates: { lat: 41.9028, lng: 12.4964 },
    domain: ".it",
    flagSVG: "ItFlag",
    gentilicio: "Italiano"
  },
  {
    idCountry: 92,
    flag: "🇯🇲",
    code: "JM",
    countryName: "Jamaica",
    cityName: "Kingston",
    phoneCode: "+1876",
    currency: "JMD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-5",
    population: 2961167,
    coordinates: { lat: 17.997, lng: -76.7936 },
    domain: ".jm",
    flagSVG: "JmFlag",
    gentilicio: "Jamaiquino"
  },
  {
    idCountry: 93,
    flag: "🇯🇵",
    code: "JP",
    countryName: "Japón",
    cityName: "Tokio",
    phoneCode: "+81",
    currency: "JPY",
    language: "Japonés",
    region: "Asia",
    timezone: "GMT+9",
    population: 126476461,
    coordinates: { lat: 35.6762, lng: 139.6503 },
    domain: ".jp",
    flagSVG: "JpFlag",
    gentilicio: "Japonés"
  },
  {
    idCountry: 94,
    flag: "🇯🇴",
    code: "JO",
    countryName: "Jordania",
    cityName: "Amán",
    phoneCode: "+962",
    currency: "JOD",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 10203134,
    coordinates: { lat: 31.9454, lng: 35.9284 },
    domain: ".jo",
    flagSVG: "JoFlag",
    gentilicio: "Jordano"
  },
  {
    idCountry: 95,
    flag: "🇰🇿",
    code: "KZ",
    countryName: "Kazajistán",
    cityName: "Astaná",
    phoneCode: "+7",
    currency: "KZT",
    language: "Kazajo, Ruso",
    region: "Asia",
    timezone: "GMT+6",
    population: 18776707,
    coordinates: { lat: 51.1694, lng: 71.4491 },
    domain: ".kz",
    flagSVG: "KzFlag",
    gentilicio: "Kazajo"
  },
  {
    idCountry: 96,
    flag: "🇰🇪",
    code: "KE",
    countryName: "Kenia",
    cityName: "Nairobi",
    phoneCode: "+254",
    currency: "KES",
    language: "Inglés, Suajili",
    region: "África",
    timezone: "GMT+3",
    population: 53771296,
    coordinates: { lat: -1.2921, lng: 36.8219 },
    domain: ".ke",
    flagSVG: "KeFlag",
    gentilicio: "Keniano"
  },
  {
    idCountry: 97,
    flag: "🇰🇬",
    code: "KG",
    countryName: "Kirguistán",
    cityName: "Biskek",
    phoneCode: "+996",
    currency: "KGS",
    language: "Kirguís, Ruso",
    region: "Asia",
    timezone: "GMT+6",
    population: 6524195,
    coordinates: { lat: 42.8746, lng: 74.5698 },
    domain: ".kg",
    flagSVG: "KgFlag",
    gentilicio: "Kirguís"
  },
  {
    idCountry: 98,
    flag: "🇰🇮",
    code: "KI",
    countryName: "Kiribati",
    cityName: "Tarawa",
    phoneCode: "+686",
    currency: "AUD",
    language: "Inglés, Gilbertés",
    region: "Oceanía",
    timezone: "GMT+12",
    population: 119449,
    coordinates: { lat: 1.4518, lng: 172.9717 },
    domain: ".ki",
    flagSVG: "KiFlag",
    gentilicio: "Kiribatiano"
  },
  {
    idCountry: 99,
    flag: "🇰🇼",
    code: "KW",
    countryName: "Kuwait",
    cityName: "Kuwait",
    phoneCode: "+965",
    currency: "KWD",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 4270571,
    coordinates: { lat: 29.3759, lng: 47.9774 },
    domain: ".kw",
    flagSVG: "KwFlag",
    gentilicio: "Kuwaití"
  },
  {
    idCountry: 100,
    flag: "🇱🇦",
    code: "LA",
    countryName: "Laos",
    cityName: "Vientián",
    phoneCode: "+856",
    currency: "LAK",
    language: "Lao",
    region: "Asia",
    timezone: "GMT+7",
    population: 7275560,
    coordinates: { lat: 17.9757, lng: 102.6331 },
    domain: ".la",
    flagSVG: "LaFlag",
    gentilicio: "Laosiano"
  },
  // PARTE 3: Países 101-150
  {
    idCountry: 101,
    flag: "🇱🇸",
    code: "LS",
    countryName: "Lesoto",
    cityName: "Maseru",
    phoneCode: "+266",
    currency: "LSL",
    language: "Inglés, Sesoto",
    region: "África",
    timezone: "GMT+2",
    population: 2142249,
    coordinates: { lat: -29.311, lng: 27.4803 },
    domain: ".ls",
    flagSVG: "LsFlag",
    gentilicio: "Lesotense"
  },
  {
    idCountry: 102,
    flag: "🇱🇻",
    code: "LV",
    countryName: "Letonia",
    cityName: "Riga",
    phoneCode: "+371",
    currency: "EUR",
    language: "Letón",
    region: "Europa",
    timezone: "GMT+3",
    population: 1886198,
    coordinates: { lat: 56.9496, lng: 24.1052 },
    domain: ".lv",
    flagSVG: "LvFlag",
    gentilicio: "Letón"
  },
  {
    idCountry: 103,
    flag: "🇱🇧",
    code: "LB",
    countryName: "Líbano",
    cityName: "Beirut",
    phoneCode: "+961",
    currency: "LBP",
    language: "Árabe, Francés",
    region: "Asia",
    timezone: "GMT+3",
    population: 6825445,
    coordinates: { lat: 33.8869, lng: 35.5131 },
    domain: ".lb",
    flagSVG: "LbFlag",
    gentilicio: "Libanés"
  },
  {
    idCountry: 104,
    flag: "🇱🇷",
    code: "LR",
    countryName: "Liberia",
    cityName: "Monrovia",
    phoneCode: "+231",
    currency: "LRD",
    language: "Inglés",
    region: "África",
    timezone: "GMT+0",
    population: 5057681,
    coordinates: { lat: 6.2907, lng: -10.7605 },
    domain: ".lr",
    flagSVG: "LrFlag",
    gentilicio: "Liberiano"
  },
  {
    idCountry: 105,
    flag: "🇱🇾",
    code: "LY",
    countryName: "Libia",
    cityName: "Trípoli",
    phoneCode: "+218",
    currency: "LYD",
    language: "Árabe",
    region: "África",
    timezone: "GMT+2",
    population: 6871292,
    coordinates: { lat: 32.8872, lng: 13.1913 },
    domain: ".ly",
    flagSVG: "LyFlag",
    gentilicio: "Libio"
  },
  {
    idCountry: 106,
    flag: "🇱🇮",
    code: "LI",
    countryName: "Liechtenstein",
    cityName: "Vaduz",
    phoneCode: "+423",
    currency: "CHF",
    language: "Alemán",
    region: "Europa",
    timezone: "GMT+2",
    population: 38128,
    coordinates: { lat: 47.166, lng: 9.5554 },
    domain: ".li",
    flagSVG: "LiFlag",
    gentilicio: "Liechtensteiniano"
  },
  {
    idCountry: 107,
    flag: "🇱🇹",
    code: "LT",
    countryName: "Lituania",
    cityName: "Vilna",
    phoneCode: "+370",
    currency: "EUR",
    language: "Lituano",
    region: "Europa",
    timezone: "GMT+3",
    population: 2722289,
    coordinates: { lat: 54.6872, lng: 25.2797 },
    domain: ".lt",
    flagSVG: "LtFlag",
    gentilicio: "Lituano"
  },
  {
    idCountry: 108,
    flag: "🇱🇺",
    code: "LU",
    countryName: "Luxemburgo",
    cityName: "Luxemburgo",
    phoneCode: "+352",
    currency: "EUR",
    language: "Luxemburgués",
    region: "Europa",
    timezone: "GMT+2",
    population: 625978,
    coordinates: { lat: 49.6117, lng: 6.1319 },
    domain: ".lu",
    flagSVG: "LuFlag",
    gentilicio: "Luxemburgués"
  },
  {
    idCountry: 109,
    flag: "🇲🇰",
    code: "MK",
    countryName: "Macedonia del Norte",
    cityName: "Skopie",
    phoneCode: "+389",
    currency: "MKD",
    language: "Macedonio",
    region: "Europa",
    timezone: "GMT+2",
    population: 2083374,
    coordinates: { lat: 41.9973, lng: 21.428 },
    domain: ".mk",
    flagSVG: "MkFlag",
    gentilicio: "Macedonio"
  },
  {
    idCountry: 110,
    flag: "🇲🇬",
    code: "MG",
    countryName: "Madagascar",
    cityName: "Antananarivo",
    phoneCode: "+261",
    currency: "MGA",
    language: "Malgache, Francés",
    region: "África",
    timezone: "GMT+3",
    population: 27691018,
    coordinates: { lat: -18.8792, lng: 47.5079 },
    domain: ".mg",
    flagSVG: "MgFlag",
    gentilicio: "Malgache"
  },
  {
    idCountry: 111,
    flag: "🇲🇾",
    code: "MY",
    countryName: "Malasia",
    cityName: "Kuala Lumpur",
    phoneCode: "+60",
    currency: "MYR",
    language: "Malayo",
    region: "Asia",
    timezone: "GMT+8",
    population: 32365999,
    coordinates: { lat: 3.139, lng: 101.6869 },
    domain: ".my",
    flagSVG: "MyFlag",
    gentilicio: "Malayo"
  },
  {
    idCountry: 112,
    flag: "🇲🇼",
    code: "MW",
    countryName: "Malaui",
    cityName: "Lilongüe",
    phoneCode: "+265",
    currency: "MWK",
    language: "Inglés, Chichewa",
    region: "África",
    timezone: "GMT+2",
    population: 19129952,
    coordinates: { lat: -13.9626, lng: 33.7741 },
    domain: ".mw",
    flagSVG: "MwFlag",
    gentilicio: "Malauí"
  },
  {
    idCountry: 113,
    flag: "🇲🇻",
    code: "MV",
    countryName: "Maldivas",
    cityName: "Malé",
    phoneCode: "+960",
    currency: "MVR",
    language: "Dhivehi",
    region: "Asia",
    timezone: "GMT+5",
    population: 540544,
    coordinates: { lat: 4.1755, lng: 73.5093 },
    domain: ".mv",
    flagSVG: "MvFlag",
    gentilicio: "Maldivo"
  },
  {
    idCountry: 114,
    flag: "🇲🇱",
    code: "ML",
    countryName: "Malí",
    cityName: "Bamako",
    phoneCode: "+223",
    currency: "XOF",
    language: "Francés",
    region: "África",
    timezone: "GMT+0",
    population: 20250833,
    coordinates: { lat: 12.6392, lng: -8.0029 },
    domain: ".ml",
    flagSVG: "MlFlag",
    gentilicio: "Maliense"
  },
  {
    idCountry: 115,
    flag: "🇲🇹",
    code: "MT",
    countryName: "Malta",
    cityName: "La Valeta",
    phoneCode: "+356",
    currency: "EUR",
    language: "Maltés, Inglés",
    region: "Europa",
    timezone: "GMT+2",
    population: 441543,
    coordinates: { lat: 35.8989, lng: 14.5146 },
    domain: ".mt",
    flagSVG: "MtFlag",
    gentilicio: "Maltés"
  },
  {
    idCountry: 116,
    flag: "🇲🇦",
    code: "MA",
    countryName: "Marruecos",
    cityName: "Rabat",
    phoneCode: "+212",
    currency: "MAD",
    language: "Árabe, Bereber",
    region: "África",
    timezone: "GMT+1",
    population: 36910560,
    coordinates: { lat: 34.0209, lng: -6.8416 },
    domain: ".ma",
    flagSVG: "MaFlag",
    gentilicio: "Marroquí"
  },
  {
    idCountry: 117,
    flag: "🇲🇺",
    code: "MU",
    countryName: "Mauricio",
    cityName: "Port Louis",
    phoneCode: "+230",
    currency: "MUR",
    language: "Inglés, Francés",
    region: "África",
    timezone: "GMT+4",
    population: 1271768,
    coordinates: { lat: -20.1609, lng: 57.5012 },
    domain: ".mu",
    flagSVG: "MuFlag",
    gentilicio: "Mauriciano"
  },
  {
    idCountry: 118,
    flag: "🇲🇷",
    code: "MR",
    countryName: "Mauritania",
    cityName: "Nuakchot",
    phoneCode: "+222",
    currency: "MRU",
    language: "Árabe",
    region: "África",
    timezone: "GMT+0",
    population: 4649658,
    coordinates: { lat: 18.0735, lng: -15.9582 },
    domain: ".mr",
    flagSVG: "MrFlag",
    gentilicio: "Mauritano"
  },
  {
    idCountry: 119,
    flag: "🇲🇽",
    code: "MX",
    countryName: "México",
    cityName: "Ciudad de México",
    phoneCode: "+52",
    currency: "MXN",
    language: "Español",
    region: "Norteamérica",
    timezone: "GMT-6",
    population: 128932753,
    coordinates: { lat: 19.4326, lng: -99.1332 },
    domain: ".mx",
    flagSVG: "MxFlag",
    gentilicio: "Mexicano"
  },
  {
    idCountry: 120,
    flag: "🇫🇲",
    code: "FM",
    countryName: "Micronesia",
    cityName: "Palikir",
    phoneCode: "+691",
    currency: "USD",
    language: "Inglés",
    region: "Oceanía",
    timezone: "GMT+10",
    population: 548914,
    coordinates: { lat: 6.9178, lng: 158.1611 },
    domain: ".fm",
    flagSVG: "FmFlag",
    gentilicio: "Micronesio"
  },
  {
    idCountry: 121,
    flag: "🇲🇩",
    code: "MD",
    countryName: "Moldavia",
    cityName: "Chisináu",
    phoneCode: "+373",
    currency: "MDL",
    language: "Rumano",
    region: "Europa",
    timezone: "GMT+3",
    population: 4033963,
    coordinates: { lat: 47.0105, lng: 28.8638 },
    domain: ".md",
    flagSVG: "MdFlag",
    gentilicio: "Moldavo"
  },
  {
    idCountry: 122,
    flag: "🇲🇨",
    code: "MC",
    countryName: "Mónaco",
    cityName: "Mónaco",
    phoneCode: "+377",
    currency: "EUR",
    language: "Francés",
    region: "Europa",
    timezone: "GMT+2",
    population: 39242,
    coordinates: { lat: 43.7384, lng: 7.4246 },
    domain: ".mc",
    flagSVG: "McFlag",
    gentilicio: "Monegasco"
  },
  {
    idCountry: 123,
    flag: "🇲🇳",
    code: "MN",
    countryName: "Mongolia",
    cityName: "Ulán Bator",
    phoneCode: "+976",
    currency: "MNT",
    language: "Mongol",
    region: "Asia",
    timezone: "GMT+8",
    population: 3278290,
    coordinates: { lat: 47.8864, lng: 106.9057 },
    domain: ".mn",
    flagSVG: "MnFlag",
    gentilicio: "Mongol"
  },
  {
    idCountry: 124,
    flag: "🇲🇪",
    code: "ME",
    countryName: "Montenegro",
    cityName: "Podgorica",
    phoneCode: "+382",
    currency: "EUR",
    language: "Montenegrino",
    region: "Europa",
    timezone: "GMT+2",
    population: 628066,
    coordinates: { lat: 42.4304, lng: 19.2594 },
    domain: ".me",
    flagSVG: "MeFlag",
    gentilicio: "Montenegrino"
  },
  {
    idCountry: 125,
    flag: "🇲🇿",
    code: "MZ",
    countryName: "Mozambique",
    cityName: "Maputo",
    phoneCode: "+258",
    currency: "MZN",
    language: "Portugués",
    region: "África",
    timezone: "GMT+2",
    population: 31255435,
    coordinates: { lat: -25.9692, lng: 32.5732 },
    domain: ".mz",
    flagSVG: "MzFlag",
    gentilicio: "Mozambiqueño"
  },
  {
    idCountry: 126,
    flag: "🇲🇲",
    code: "MM",
    countryName: "Myanmar",
    cityName: "Naipyidó",
    phoneCode: "+95",
    currency: "MMK",
    language: "Birmano",
    region: "Asia",
    timezone: "GMT+6:30",
    population: 54409800,
    coordinates: { lat: 19.7633, lng: 96.0785 },
    domain: ".mm",
    flagSVG: "MmFlag",
    gentilicio: "Birmano"
  },
  {
    idCountry: 127,
    flag: "🇳🇦",
    code: "NA",
    countryName: "Namibia",
    cityName: "Windhoek",
    phoneCode: "+264",
    currency: "NAD",
    language: "Inglés",
    region: "África",
    timezone: "GMT+2",
    population: 2540905,
    coordinates: { lat: -22.5597, lng: 17.0832 },
    domain: ".na",
    flagSVG: "NaFlag",
    gentilicio: "Namibio"
  },
  {
    idCountry: 128,
    flag: "🇳🇷",
    code: "NR",
    countryName: "Nauru",
    cityName: "Yaren",
    phoneCode: "+674",
    currency: "AUD",
    language: "Inglés, Nauruano",
    region: "Oceanía",
    timezone: "GMT+12",
    population: 10824,
    coordinates: { lat: -0.5228, lng: 166.9315 },
    domain: ".nr",
    flagSVG: "NrFlag",
    gentilicio: "Nauruano"
  },
  {
    idCountry: 129,
    flag: "🇳🇵",
    code: "NP",
    countryName: "Nepal",
    cityName: "Katmandú",
    phoneCode: "+977",
    currency: "NPR",
    language: "Nepalí",
    region: "Asia",
    timezone: "GMT+5:45",
    population: 29136808,
    coordinates: { lat: 27.7172, lng: 85.324 },
    domain: ".np",
    flagSVG: "NpFlag",
    gentilicio: "Nepalí"
  },
  {
    idCountry: 130,
    flag: "🇳🇮",
    code: "NI",
    countryName: "Nicaragua",
    cityName: "Managua",
    phoneCode: "+505",
    currency: "NIO",
    language: "Español",
    region: "Centroamérica",
    timezone: "GMT-6",
    population: 6624554,
    coordinates: { lat: 12.1364, lng: -86.2514 },
    domain: ".ni",
    flagSVG: "NiFlag",
    gentilicio: "Nicaragüense"
  },
  {
    idCountry: 131,
    flag: "🇳🇪",
    code: "NE",
    countryName: "Níger",
    cityName: "Niamey",
    phoneCode: "+227",
    currency: "XOF",
    language: "Francés",
    region: "África",
    timezone: "GMT+1",
    population: 24206644,
    coordinates: { lat: 13.5116, lng: 2.1254 },
    domain: ".ne",
    flagSVG: "NeFlag",
    gentilicio: "Nigerino"
  },
  {
    idCountry: 132,
    flag: "🇳🇬",
    code: "NG",
    countryName: "Nigeria",
    cityName: "Abuja",
    phoneCode: "+234",
    currency: "NGN",
    language: "Inglés",
    region: "África",
    timezone: "GMT+1",
    population: 206139589,
    coordinates: { lat: 9.0579, lng: 7.4951 },
    domain: ".ng",
    flagSVG: "NgFlag",
    gentilicio: "Nigeriano"
  },
  {
    idCountry: 133,
    flag: "🇳🇴",
    code: "NO",
    countryName: "Noruega",
    cityName: "Oslo",
    phoneCode: "+47",
    currency: "NOK",
    language: "Noruego",
    region: "Europa",
    timezone: "GMT+2",
    population: 5421241,
    coordinates: { lat: 59.9139, lng: 10.7522 },
    domain: ".no",
    flagSVG: "NoFlag",
    gentilicio: "Noruego"
  },
  {
    idCountry: 134,
    flag: "🇳🇿",
    code: "NZ",
    countryName: "Nueva Zelanda",
    cityName: "Wellington",
    phoneCode: "+64",
    currency: "NZD",
    language: "Inglés, Maorí",
    region: "Oceanía",
    timezone: "GMT+12",
    population: 4822233,
    coordinates: { lat: -41.2865, lng: 174.7762 },
    domain: ".nz",
    flagSVG: "NzFlag",
    gentilicio: "Neozelandés"
  },
  {
    idCountry: 135,
    flag: "🇴🇲",
    code: "OM",
    countryName: "Omán",
    cityName: "Mascate",
    phoneCode: "+968",
    currency: "OMR",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+4",
    population: 5106626,
    coordinates: { lat: 23.5859, lng: 58.4059 },
    domain: ".om",
    flagSVG: "OmFlag",
    gentilicio: "Omaní"
  },
  {
    idCountry: 136,
    flag: "🇳🇱",
    code: "NL",
    countryName: "Países Bajos",
    cityName: "Ámsterdam",
    phoneCode: "+31",
    currency: "EUR",
    language: "Neerlandés",
    region: "Europa",
    timezone: "GMT+2",
    population: 17134872,
    coordinates: { lat: 52.3676, lng: 4.9041 },
    domain: ".nl",
    flagSVG: "NlFlag",
    gentilicio: "Neerlandés"
  },
  {
    idCountry: 137,
    flag: "🇵🇰",
    code: "PK",
    countryName: "Pakistán",
    cityName: "Islamabad",
    phoneCode: "+92",
    currency: "PKR",
    language: "Urdu, Inglés",
    region: "Asia",
    timezone: "GMT+5",
    population: 220892340,
    coordinates: { lat: 33.7294, lng: 73.0931 },
    domain: ".pk",
    flagSVG: "PkFlag",
    gentilicio: "Pakistaní"
  },
  {
    idCountry: 138,
    flag: "🇵🇼",
    code: "PW",
    countryName: "Palaos",
    cityName: "Ngerulmud",
    phoneCode: "+680",
    currency: "USD",
    language: "Inglés, Palauano",
    region: "Oceanía",
    timezone: "GMT+9",
    population: 18094,
    coordinates: { lat: 7.5006, lng: 134.6242 },
    domain: ".pw",
    flagSVG: "PwFlag",
    gentilicio: "Palauano"
  },
  {
    idCountry: 139,
    flag: "🇵🇸",
    code: "PS",
    countryName: "Palestina",
    cityName: "Ramala",
    phoneCode: "+970",
    currency: "ILS",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 5101414,
    coordinates: { lat: 31.9073, lng: 35.2044 },
    domain: ".ps",
    flagSVG: "PsFlag",
    gentilicio: "Palestino"
  },
  {
    idCountry: 140,
    flag: "🇵🇦",
    code: "PA",
    countryName: "Panamá",
    cityName: "Panamá",
    phoneCode: "+507",
    currency: "PAB",
    language: "Español",
    region: "Centroamérica",
    timezone: "GMT-5",
    population: 4314767,
    coordinates: { lat: 8.538, lng: -80.7821 },
    domain: ".pa",
    flagSVG: "PaFlag",
    gentilicio: "Panameño"
  },
  {
    idCountry: 141,
    flag: "🇵🇬",
    code: "PG",
    countryName: "Papúa Nueva Guinea",
    cityName: "Port Moresby",
    phoneCode: "+675",
    currency: "PGK",
    language: "Inglés",
    region: "Oceanía",
    timezone: "GMT+10",
    population: 8947024,
    coordinates: { lat: -9.4438, lng: 147.1803 },
    domain: ".pg",
    flagSVG: "PgFlag",
    gentilicio: "Papú"
  },
  {
    idCountry: 142,
    flag: "🇵🇾",
    code: "PY",
    countryName: "Paraguay",
    cityName: "Asunción",
    phoneCode: "+595",
    currency: "PYG",
    language: "Español, Guaraní",
    region: "Sudamérica",
    timezone: "GMT-3",
    population: 7132538,
    coordinates: { lat: -25.2637, lng: -57.5759 },
    domain: ".py",
    flagSVG: "PyFlag",
    gentilicio: "Paraguayo"
  },
  {
    idCountry: 143,
    flag: "🇵🇪",
    code: "PE",
    countryName: "Perú",
    cityName: "Lima",
    phoneCode: "+51",
    currency: "PEN",
    language: "Español",
    region: "Sudamérica",
    timezone: "GMT-5",
    population: 32971854,
    coordinates: { lat: -12.0464, lng: -77.0428 },
    domain: ".pe",
    flagSVG: "PeFlag",
    gentilicio: "Peruano"
  },
  {
    idCountry: 144,
    flag: "🇵🇱",
    code: "PL",
    countryName: "Polonia",
    cityName: "Varsovia",
    phoneCode: "+48",
    currency: "PLN",
    language: "Polaco",
    region: "Europa",
    timezone: "GMT+2",
    population: 37846611,
    coordinates: { lat: 52.2297, lng: 21.0122 },
    domain: ".pl",
    flagSVG: "PlFlag",
    gentilicio: "Polaco"
  },
  {
    idCountry: 145,
    flag: "🇵🇹",
    code: "PT",
    countryName: "Portugal",
    cityName: "Lisboa",
    phoneCode: "+351",
    currency: "EUR",
    language: "Portugués",
    region: "Europa",
    timezone: "GMT+1",
    population: 10196709,
    coordinates: { lat: 38.7223, lng: -9.1393 },
    domain: ".pt",
    flagSVG: "PtFlag",
    gentilicio: "Portugués"
  },
  {
    idCountry: 146,
    flag: "🇬🇧",
    code: "GB",
    countryName: "Reino Unido",
    cityName: "Londres",
    phoneCode: "+44",
    currency: "GBP",
    language: "Inglés",
    region: "Europa",
    timezone: "GMT+1",
    population: 67886011,
    coordinates: { lat: 51.5074, lng: -0.1278 },
    domain: ".uk",
    flagSVG: "GbFlag",
    gentilicio: "Británico"
  },
  {
    idCountry: 147,
    flag: "🇨🇫",
    code: "CF",
    countryName: "República Centroafricana",
    cityName: "Bangui",
    phoneCode: "+236",
    currency: "XAF",
    language: "Francés, Sango",
    region: "África",
    timezone: "GMT+1",
    population: 4829767,
    coordinates: { lat: 4.3947, lng: 18.5582 },
    domain: ".cf",
    flagSVG: "CfFlag",
    gentilicio: "Centroafricano"
  },
  {
    idCountry: 148,
    flag: "🇨🇿",
    code: "CZ",
    countryName: "República Checa",
    cityName: "Praga",
    phoneCode: "+420",
    currency: "CZK",
    language: "Checo",
    region: "Europa",
    timezone: "GMT+2",
    population: 10708981,
    coordinates: { lat: 50.0755, lng: 14.4378 },
    domain: ".cz",
    flagSVG: "CzFlag",
    gentilicio: "Checo"
  },
  {
    idCountry: 149,
    flag: "🇨🇩",
    code: "CD",
    countryName: "República Democrática del Congo",
    cityName: "Kinshasa",
    phoneCode: "+243",
    currency: "CDF",
    language: "Francés",
    region: "África",
    timezone: "GMT+1",
    population: 89561403,
    coordinates: { lat: -4.4419, lng: 15.2663 },
    domain: ".cd",
    flagSVG: "CdFlag",
    gentilicio: "Congoleño"
  },
  {
    idCountry: 150,
    flag: "🇨🇬",
    code: "CG",
    countryName: "República del Congo",
    cityName: "Brazzaville",
    phoneCode: "+242",
    currency: "XAF",
    language: "Francés",
    region: "África",
    timezone: "GMT+1",
    population: 5518087,
    coordinates: { lat: -4.2634, lng: 15.2429 },
    domain: ".cg",
    flagSVG: "CgFlag",
    gentilicio: "Congoleño"
  },
  // PARTE 4: Países 151-196
  {
    idCountry: 151,
    flag: "🇷🇴",
    code: "RO",
    countryName: "Rumania",
    cityName: "Bucarest",
    phoneCode: "+40",
    currency: "RON",
    language: "Rumano",
    region: "Europa",
    timezone: "GMT+3",
    population: 19237691,
    coordinates: { lat: 44.4268, lng: 26.1025 },
    domain: ".ro",
    flagSVG: "RoFlag",
    gentilicio: "Rumano"
  },
  {
    idCountry: 152,
    flag: "🇷🇺",
    code: "RU",
    countryName: "Rusia",
    cityName: "Moscú",
    phoneCode: "+7",
    currency: "RUB",
    language: "Ruso",
    region: "Europa/Asia",
    timezone: "GMT+3 a GMT+12",
    population: 145934462,
    coordinates: { lat: 55.7558, lng: 37.6173 },
    domain: ".ru",
    flagSVG: "RuFlag",
    gentilicio: "Ruso"
  },
  {
    idCountry: 153,
    flag: "🇷🇼",
    code: "RW",
    countryName: "Ruanda",
    cityName: "Kigali",
    phoneCode: "+250",
    currency: "RWF",
    language: "Kinyarwanda",
    region: "África",
    timezone: "GMT+2",
    population: 12952218,
    coordinates: { lat: -1.9441, lng: 30.0619 },
    domain: ".rw",
    flagSVG: "RwFlag",
    gentilicio: "Ruandés"
  },
  {
    idCountry: 154,
    flag: "🇼🇸",
    code: "WS",
    countryName: "Samoa",
    cityName: "Apia",
    phoneCode: "+685",
    currency: "WST",
    language: "Samoano, Inglés",
    region: "Oceanía",
    timezone: "GMT+13",
    population: 198414,
    coordinates: { lat: -13.8506, lng: -171.7513 },
    domain: ".ws",
    flagSVG: "WsFlag",
    gentilicio: "Samoano"
  },
  {
    idCountry: 155,
    flag: "🇰🇳",
    code: "KN",
    countryName: "San Cristóbal y Nieves",
    cityName: "Basseterre",
    phoneCode: "+1869",
    currency: "XCD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 53199,
    coordinates: { lat: 17.3026, lng: -62.7177 },
    domain: ".kn",
    flagSVG: "KnFlag",
    gentilicio: "Sancristobaleño"
  },
  {
    idCountry: 156,
    flag: "🇸🇲",
    code: "SM",
    countryName: "San Marino",
    cityName: "San Marino",
    phoneCode: "+378",
    currency: "EUR",
    language: "Italiano",
    region: "Europa",
    timezone: "GMT+2",
    population: 33931,
    coordinates: { lat: 43.9424, lng: 12.4578 },
    domain: ".sm",
    flagSVG: "SmFlag",
    gentilicio: "Sanmarinense"
  },
  {
    idCountry: 157,
    flag: "🇻🇨",
    code: "VC",
    countryName: "San Vicente y las Granadinas",
    cityName: "Kingstown",
    phoneCode: "+1784",
    currency: "XCD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 110940,
    coordinates: { lat: 13.16, lng: -61.2248 },
    domain: ".vc",
    flagSVG: "VcFlag",
    gentilicio: "Sanvicentino"
  },
  {
    idCountry: 158,
    flag: "🇱🇨",
    code: "LC",
    countryName: "Santa Lucía",
    cityName: "Castries",
    phoneCode: "+1758",
    currency: "XCD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 183627,
    coordinates: { lat: 14.0101, lng: -60.9875 },
    domain: ".lc",
    flagSVG: "LcFlag",
    gentilicio: "Santalucense"
  },
  {
    idCountry: 159,
    flag: "🇸🇹",
    code: "ST",
    countryName: "Santo Tomé y Príncipe",
    cityName: "Santo Tomé",
    phoneCode: "+239",
    currency: "STN",
    language: "Portugués",
    region: "África",
    timezone: "GMT+0",
    population: 219159,
    coordinates: { lat: 0.1864, lng: 6.6131 },
    domain: ".st",
    flagSVG: "StFlag",
    gentilicio: "Santotomense"
  },
  {
    idCountry: 160,
    flag: "🇸🇳",
    code: "SN",
    countryName: "Senegal",
    cityName: "Dakar",
    phoneCode: "+221",
    currency: "XOF",
    language: "Francés",
    region: "África",
    timezone: "GMT+0",
    population: 16743927,
    coordinates: { lat: 14.7167, lng: -17.4677 },
    domain: ".sn",
    flagSVG: "SnFlag",
    gentilicio: "Senegalés"
  },
  {
    idCountry: 161,
    flag: "🇷🇸",
    code: "RS",
    countryName: "Serbia",
    cityName: "Belgrado",
    phoneCode: "+381",
    currency: "RSD",
    language: "Serbio",
    region: "Europa",
    timezone: "GMT+2",
    population: 8737371,
    coordinates: { lat: 44.7866, lng: 20.4489 },
    domain: ".rs",
    flagSVG: "RsFlag",
    gentilicio: "Serbio"
  },
  {
    idCountry: 162,
    flag: "🇸🇨",
    code: "SC",
    countryName: "Seychelles",
    cityName: "Victoria",
    phoneCode: "+248",
    currency: "SCR",
    language: "Inglés, Francés",
    region: "África",
    timezone: "GMT+4",
    population: 98347,
    coordinates: { lat: -4.6574, lng: 55.454 },
    domain: ".sc",
    flagSVG: "ScFlag",
    gentilicio: "Seychellense"
  },
  {
    idCountry: 163,
    flag: "🇸🇱",
    code: "SL",
    countryName: "Sierra Leona",
    cityName: "Freetown",
    phoneCode: "+232",
    currency: "SLE",
    language: "Inglés",
    region: "África",
    timezone: "GMT+0",
    population: 7976983,
    coordinates: { lat: 8.4606, lng: -13.2317 },
    domain: ".sl",
    flagSVG: "SlFlag",
    gentilicio: "Sierraleonés"
  },
  {
    idCountry: 164,
    flag: "🇸🇬",
    code: "SG",
    countryName: "Singapur",
    cityName: "Singapur",
    phoneCode: "+65",
    currency: "SGD",
    language: "Inglés, Mandarín",
    region: "Asia",
    timezone: "GMT+8",
    population: 5850342,
    coordinates: { lat: 1.3521, lng: 103.8198 },
    domain: ".sg",
    flagSVG: "SgFlag",
    gentilicio: "Singapurense"
  },
  {
    idCountry: 165,
    flag: "🇸🇾",
    code: "SY",
    countryName: "Siria",
    cityName: "Damasco",
    phoneCode: "+963",
    currency: "SYP",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 17500658,
    coordinates: { lat: 33.5138, lng: 36.2765 },
    domain: ".sy",
    flagSVG: "SyFlag",
    gentilicio: "Sirio"
  },
  {
    idCountry: 166,
    flag: "🇸🇴",
    code: "SO",
    countryName: "Somalia",
    cityName: "Mogadiscio",
    phoneCode: "+252",
    currency: "SOS",
    language: "Somalí, Árabe",
    region: "África",
    timezone: "GMT+3",
    population: 15893222,
    coordinates: { lat: 2.0469, lng: 45.3182 },
    domain: ".so",
    flagSVG: "SoFlag",
    gentilicio: "Somalí"
  },
  {
    idCountry: 167,
    flag: "🇱🇰",
    code: "LK",
    countryName: "Sri Lanka",
    cityName: "Colombo",
    phoneCode: "+94",
    currency: "LKR",
    language: "Cingalés, Tamil",
    region: "Asia",
    timezone: "GMT+5:30",
    population: 21413249,
    coordinates: { lat: 6.9271, lng: 79.8612 },
    domain: ".lk",
    flagSVG: "LkFlag",
    gentilicio: "Cingalés"
  },
  {
    idCountry: 168,
    flag: "🇿🇦",
    code: "ZA",
    countryName: "Sudáfrica",
    cityName: "Pretoria",
    phoneCode: "+27",
    currency: "ZAR",
    language: "Inglés, Afrikáans",
    region: "África",
    timezone: "GMT+2",
    population: 59308690,
    coordinates: { lat: -25.7461, lng: 28.1881 },
    domain: ".za",
    flagSVG: "ZaFlag",
    gentilicio: "Sudafricano"
  },
  {
    idCountry: 169,
    flag: "🇸🇩",
    code: "SD",
    countryName: "Sudán",
    cityName: "Jartum",
    phoneCode: "+249",
    currency: "SDG",
    language: "Árabe",
    region: "África",
    timezone: "GMT+2",
    population: 43849260,
    coordinates: { lat: 15.5007, lng: 32.5599 },
    domain: ".sd",
    flagSVG: "SdFlag",
    gentilicio: "Sudanés"
  },
  {
    idCountry: 170,
    flag: "🇸🇸",
    code: "SS",
    countryName: "Sudán del Sur",
    cityName: "Yuba",
    phoneCode: "+211",
    currency: "SSP",
    language: "Inglés",
    region: "África",
    timezone: "GMT+3",
    population: 11193725,
    coordinates: { lat: 4.8594, lng: 31.5713 },
    domain: ".ss",
    flagSVG: "SsFlag",
    gentilicio: "Sursudanés"
  },
  {
    idCountry: 171,
    flag: "🇸🇪",
    code: "SE",
    countryName: "Suecia",
    cityName: "Estocolmo",
    phoneCode: "+46",
    currency: "SEK",
    language: "Sueco",
    region: "Europa",
    timezone: "GMT+2",
    population: 10099265,
    coordinates: { lat: 59.3293, lng: 18.0686 },
    domain: ".se",
    flagSVG: "SeFlag",
    gentilicio: "Sueco"
  },
  {
    idCountry: 172,
    flag: "🇨🇭",
    code: "CH",
    countryName: "Suiza",
    cityName: "Berna",
    phoneCode: "+41",
    currency: "CHF",
    language: "Alemán, Francés",
    region: "Europa",
    timezone: "GMT+2",
    population: 8654622,
    coordinates: { lat: 46.9481, lng: 7.4474 },
    domain: ".ch",
    flagSVG: "ChFlag",
    gentilicio: "Suizo"
  },
  {
    idCountry: 173,
    flag: "🇸🇷",
    code: "SR",
    countryName: "Surinam",
    cityName: "Paramaribo",
    phoneCode: "+597",
    currency: "SRD",
    language: "Neerlandés",
    region: "Sudamérica",
    timezone: "GMT-3",
    population: 586632,
    coordinates: { lat: 5.852, lng: -55.2038 },
    domain: ".sr",
    flagSVG: "SrFlag",
    gentilicio: "Surinamés"
  },
  {
    idCountry: 174,
    flag: "🇹🇭",
    code: "TH",
    countryName: "Tailandia",
    cityName: "Bangkok",
    phoneCode: "+66",
    currency: "THB",
    language: "Tailandés",
    region: "Asia",
    timezone: "GMT+7",
    population: 69799978,
    coordinates: { lat: 13.7563, lng: 100.5018 },
    domain: ".th",
    flagSVG: "ThFlag",
    gentilicio: "Tailandés"
  },
  {
    idCountry: 175,
    flag: "🇹🇼",
    code: "TW",
    countryName: "Taiwán",
    cityName: "Taipéi",
    phoneCode: "+886",
    currency: "TWD",
    language: "Chino",
    region: "Asia",
    timezone: "GMT+8",
    population: 23816775,
    coordinates: { lat: 25.033, lng: 121.5654 },
    domain: ".tw",
    flagSVG: "TwFlag",
    gentilicio: "Taiwanés"
  },
  {
    idCountry: 176,
    flag: "🇹🇿",
    code: "TZ",
    countryName: "Tanzania",
    cityName: "Dodoma",
    phoneCode: "+255",
    currency: "TZS",
    language: "Suajili, Inglés",
    region: "África",
    timezone: "GMT+3",
    population: 59734218,
    coordinates: { lat: -6.163, lng: 35.7516 },
    domain: ".tz",
    flagSVG: "TzFlag",
    gentilicio: "Tanzano"
  },
  {
    idCountry: 177,
    flag: "🇹🇯",
    code: "TJ",
    countryName: "Tayikistán",
    cityName: "Dusambé",
    phoneCode: "+992",
    currency: "TJS",
    language: "Tayiko",
    region: "Asia",
    timezone: "GMT+5",
    population: 9537645,
    coordinates: { lat: 38.5598, lng: 68.787 },
    domain: ".tj",
    flagSVG: "TjFlag",
    gentilicio: "Tayiko"
  },
  {
    idCountry: 178,
    flag: "🇹🇱",
    code: "TL",
    countryName: "Timor Oriental",
    cityName: "Dili",
    phoneCode: "+670",
    currency: "USD",
    language: "Tetún, Portugués",
    region: "Asia",
    timezone: "GMT+9",
    population: 1318445,
    coordinates: { lat: -8.5569, lng: 125.5603 },
    domain: ".tl",
    flagSVG: "TlFlag",
    gentilicio: "Timorense"
  },
  {
    idCountry: 179,
    flag: "🇹🇬",
    code: "TG",
    countryName: "Togo",
    cityName: "Lomé",
    phoneCode: "+228",
    currency: "XOF",
    language: "Francés",
    region: "África",
    timezone: "GMT+0",
    population: 8278724,
    coordinates: { lat: 6.1728, lng: 1.2255 },
    domain: ".tg",
    flagSVG: "TgFlag",
    gentilicio: "Togolés"
  },
  {
    idCountry: 180,
    flag: "🇹🇴",
    code: "TO",
    countryName: "Tonga",
    cityName: "Nukualofa",
    phoneCode: "+676",
    currency: "TOP",
    language: "Tongano, Inglés",
    region: "Oceanía",
    timezone: "GMT+13",
    population: 105695,
    coordinates: { lat: -21.1789, lng: -175.1982 },
    domain: ".to",
    flagSVG: "ToFlag",
    gentilicio: "Tongano"
  },
  {
    idCountry: 181,
    flag: "🇹🇹",
    code: "TT",
    countryName: "Trinidad y Tobago",
    cityName: "Puerto España",
    phoneCode: "+1868",
    currency: "TTD",
    language: "Inglés",
    region: "Caribe",
    timezone: "GMT-4",
    population: 1399488,
    coordinates: { lat: 10.6918, lng: -61.2225 },
    domain: ".tt",
    flagSVG: "TtFlag",
    gentilicio: "Trinitense"
  },
  {
    idCountry: 182,
    flag: "🇹🇳",
    code: "TN",
    countryName: "Túnez",
    cityName: "Túnez",
    phoneCode: "+216",
    currency: "TND",
    language: "Árabe",
    region: "África",
    timezone: "GMT+1",
    population: 11818619,
    coordinates: { lat: 36.8065, lng: 10.1815 },
    domain: ".tn",
    flagSVG: "TnFlag",
    gentilicio: "Tunecino"
  },
  {
    idCountry: 183,
    flag: "🇹🇲",
    code: "TM",
    countryName: "Turkmenistán",
    cityName: "Asjabad",
    phoneCode: "+993",
    currency: "TMT",
    language: "Turcomano",
    region: "Asia",
    timezone: "GMT+5",
    population: 6031200,
    coordinates: { lat: 37.9601, lng: 58.3261 },
    domain: ".tm",
    flagSVG: "TmFlag",
    gentilicio: "Turcomano"
  },
  {
    idCountry: 184,
    flag: "🇹🇷",
    code: "TR",
    countryName: "Turquía",
    cityName: "Ankara",
    phoneCode: "+90",
    currency: "TRY",
    language: "Turco",
    region: "Europa/Asia",
    timezone: "GMT+3",
    population: 84339067,
    coordinates: { lat: 39.9334, lng: 32.8597 },
    domain: ".tr",
    flagSVG: "TrFlag",
    gentilicio: "Turco"
  },
  {
    idCountry: 185,
    flag: "🇹🇻",
    code: "TV",
    countryName: "Tuvalu",
    cityName: "Funafuti",
    phoneCode: "+688",
    currency: "AUD",
    language: "Inglés, Tuvaluano",
    region: "Oceanía",
    timezone: "GMT+12",
    population: 11792,
    coordinates: { lat: -8.5211, lng: 179.1982 },
    domain: ".tv",
    flagSVG: "TvFlag",
    gentilicio: "Tuvaluano"
  },
  {
    idCountry: 186,
    flag: "🇺🇦",
    code: "UA",
    countryName: "Ucrania",
    cityName: "Kiev",
    phoneCode: "+380",
    currency: "UAH",
    language: "Ucraniano",
    region: "Europa",
    timezone: "GMT+3",
    population: 43733762,
    coordinates: { lat: 50.4501, lng: 30.5234 },
    domain: ".ua",
    flagSVG: "UaFlag",
    gentilicio: "Ucraniano"
  },
  {
    idCountry: 187,
    flag: "🇺🇬",
    code: "UG",
    countryName: "Uganda",
    cityName: "Kampala",
    phoneCode: "+256",
    currency: "UGX",
    language: "Inglés, Suajili",
    region: "África",
    timezone: "GMT+3",
    population: 45741007,
    coordinates: { lat: 0.3476, lng: 32.5825 },
    domain: ".ug",
    flagSVG: "UgFlag",
    gentilicio: "Ugandés"
  },
  {
    idCountry: 188,
    flag: "🇺🇾",
    code: "UY",
    countryName: "Uruguay",
    cityName: "Montevideo",
    phoneCode: "+598",
    currency: "UYU",
    language: "Español",
    region: "Sudamérica",
    timezone: "GMT-3",
    population: 3473730,
    coordinates: { lat: -34.9011, lng: -56.1645 },
    domain: ".uy",
    flagSVG: "UyFlag",
    gentilicio: "Uruguayo"
  },
  {
    idCountry: 189,
    flag: "🇺🇿",
    code: "UZ",
    countryName: "Uzbekistán",
    cityName: "Taskent",
    phoneCode: "+998",
    currency: "UZS",
    language: "Uzbeko",
    region: "Asia",
    timezone: "GMT+5",
    population: 33469203,
    coordinates: { lat: 41.2995, lng: 69.2401 },
    domain: ".uz",
    flagSVG: "UzFlag",
    gentilicio: "Uzbeko"
  },
  {
    idCountry: 190,
    flag: "🇻🇺",
    code: "VU",
    countryName: "Vanuatu",
    cityName: "Port Vila",
    phoneCode: "+678",
    currency: "VUV",
    language: "Inglés, Francés",
    region: "Oceanía",
    timezone: "GMT+11",
    population: 307145,
    coordinates: { lat: -17.7334, lng: 168.3273 },
    domain: ".vu",
    flagSVG: "VuFlag",
    gentilicio: "Vanuatuense"
  },
  {
    idCountry: 191,
    flag: "🇻🇪",
    code: "VE",
    countryName: "Venezuela",
    cityName: "Caracas",
    phoneCode: "+58",
    currency: "VES",
    language: "Español",
    region: "Sudamérica",
    timezone: "GMT-4",
    population: 28435940,
    coordinates: { lat: 10.4806, lng: -66.9036 },
    domain: ".ve",
    flagSVG: "VeFlag",
    gentilicio: "Venezolano"
  },
  {
    idCountry: 192,
    flag: "🇻🇳",
    code: "VN",
    countryName: "Vietnam",
    cityName: "Hanói",
    phoneCode: "+84",
    currency: "VND",
    language: "Vietnamita",
    region: "Asia",
    timezone: "GMT+7",
    population: 97338579,
    coordinates: { lat: 21.0285, lng: 105.8542 },
    domain: ".vn",
    flagSVG: "VnFlag",
    gentilicio: "Vietnamita"
  },
  {
    idCountry: 193,
    flag: "🇾🇪",
    code: "YE",
    countryName: "Yemen",
    cityName: "Saná",
    phoneCode: "+967",
    currency: "YER",
    language: "Árabe",
    region: "Asia",
    timezone: "GMT+3",
    population: 29825964,
    coordinates: { lat: 15.3694, lng: 44.191 },
    domain: ".ye",
    flagSVG: "YeFlag",
    gentilicio: "Yemení"
  },
  {
    idCountry: 194,
    flag: "🇩🇯",
    code: "DJ",
    countryName: "Yibuti",
    cityName: "Yibuti",
    phoneCode: "+253",
    currency: "DJF",
    language: "Francés, Árabe",
    region: "África",
    timezone: "GMT+3",
    population: 988000,
    coordinates: { lat: 11.5886, lng: 43.145 },
    domain: ".dj",
    flagSVG: "DjFlag",
    gentilicio: "Yibutiano"
  },
  {
    idCountry: 195,
    flag: "🇿🇲",
    code: "ZM",
    countryName: "Zambia",
    cityName: "Lusaka",
    phoneCode: "+260",
    currency: "ZMW",
    language: "Inglés",
    region: "África",
    timezone: "GMT+2",
    population: 18383955,
    coordinates: { lat: -15.3875, lng: 28.3228 },
    domain: ".zm",
    flagSVG: "ZmFlag",
    gentilicio: "Zambiano"
  },
  {
    idCountry: 196,
    flag: "🇿🇼",
    code: "ZW",
    countryName: "Zimbabue",
    cityName: "Harare",
    phoneCode: "+263",
    currency: "ZWL",
    language: "Inglés, Shona",
    region: "África",
    timezone: "GMT+2",
    population: 14862924,
    coordinates: { lat: -17.8252, lng: 31.0335 },
    domain: ".zw",
    flagSVG: "ZwFlag",
    gentilicio: "Zimbabuense"
  }
];

export { countriesData };
